### ISSUE TITLE
svg export removed foreignObject, How can fix that ?

### ISSUE THREAD

**Issue by meganathan-codenatives** [sharonchoong/svg-exportJS#4]
`<svg id="mysvg" height="400" width="100%">
    <g class="rects">
        <rect x="300" y="40" width="40" height="40" fill="black" stroke="black"></rect>
        <rect x="50" y="100" width="500" height="200" fill="orange" stroke="gray" opacity="0.5"></rect>
    </g>
    <g class="circles">
        <circle cx="100" cy="100" r="100" fill="green" stroke="yellow" opacity="0.2"></circle>
        <circle cx="200" cy="100" r="50" fill="#778899" stroke="blue" opacity="0.5"></circle>
        <circle cx="400" cy="200" r="150" fill="transparent" stroke="currentColor" opacity="0.8"></circle>
    </g>
    <text x="200" y="200" style="font-family: 'Segan', Arial;" font-size="20">Testing 123</text>
    <foreignObject x="100" y="25"
        width="160" height="160">
        <div>
            <br><br>GEEKSFORGEEKS<br><br>
        </div>
    </foreignObject>
</svg>`

**Comment by sharonchoong** [comment]
Both Canvg (image export) and SVG-to-PDFKit (PDF export) libraries do not support foreignObject out-of-the-box because the contents of foreignObject are not SVG.  Please see the relevant closed issues for [canvg](https://github.com/canvg/canvg/issues/1383) and [SVG-to-PDFKit](https://github.com/alafr/SVG-to-PDFKit/issues/37).

A potential solution for you was mentioned in those issues -- convert the text in foreignObject into text elements, or convert the html in foreignObject into an image using [html2canvas](https://github.com/niklasvh/html2canvas).  

In any case, this issue will be closed because it is out of scope of svg-exportJS.
